'use strict';
/**
 * EsgMetric.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Mongoose model for the ESGLink Metric Library.
 *
 * Design goals:
 *   - Minimal schema covering §1.1 / §1.2 / §1.3 / §2.1 / §2.2 / §2.10 of
 *     the ESGLink Metric Dictionary (v1).
 *   - Global metrics (isGlobal: true)  — created by consultant_admin / super_admin.
 *   - Client-scoped custom metrics (isGlobal: false) — created by consultant
 *     for a specific client; immediately published on creation.
 *   - Formula integration via formulaId reference only (no variable mapping —
 *     frozen/realtime/manual mode mapping is deferred to Step 3).
 *   - Assignment (contributor / reviewers / approvers) is deferred to Step 3
 *     (metric-to-boundary mapping stage).
 *   - No field-level encryption — metric definitions are library catalog data,
 *     not sensitive operational client data.
 */

const mongoose = require('mongoose');

// ── Subcategory code register (§1.3 of Metric Dictionary) ─────────────────────
// Used for validation — must stay in sync with the metric dictionary.
const SUBCATEGORY_CODES = {
  E: ['EN', 'GH', 'WA', 'WS', 'BD', 'AC'],
  S: ['EW', 'OHS', 'DI', 'TN', 'HR', 'SC', 'SH', 'CSR', 'CS'],
  G: ['ET', 'GB', 'CP', 'PP', 'OP'],
};

const METRIC_TYPE_ENUM        = ['raw', 'derived', 'intensity', 'client_defined'];
const ESG_CATEGORY_ENUM       = ['E', 'S', 'G'];
const DATA_TYPE_ENUM          = ['number', 'text', 'boolean', 'enum', 'date', 'mixed'];
const PUBLISHED_STATUS_ENUM   = ['draft', 'published', 'retired'];

// ── Schema ─────────────────────────────────────────────────────────────────────

const esgMetricSchema = new mongoose.Schema(
  {
    // ── Identity (§2.1 + §1.1 + §1.2 + §1.3) ─────────────────────────────────
    metricCode: {
      type: String,
      trim: true,
      // e.g. ESG-E-EN-001. Auto-generated by metricService.generateMetricCode().
      // Unique per scope: global metrics share one namespace; each client has its own.
      // sparse allows null during creation before code is assigned, but enforced
      // as non-null before save (controller responsibility).
    },
    metricName: {
      type: String,
      required: [true, 'metricName is required'],
      trim: true,
    },
    metricDescription: {
      type: String,
      trim: true,
      default: null,
    },
    esgCategory: {
      type: String,
      enum: ESG_CATEGORY_ENUM,
      required: [true, 'esgCategory is required (E | S | G)'],
    },
    subcategoryCode: {
      type: String,
      required: [true, 'subcategoryCode is required'],
      // Validated against SUBCATEGORY_CODES map in the controller / service layer.
      // Storing as a plain string (not enum) so the register can expand without
      // schema migration.
    },
    metricType: {
      type: String,
      enum: METRIC_TYPE_ENUM,
      required: [true, 'metricType is required'],
    },

    // ── Scope ─────────────────────────────────────────────────────────────────
    isGlobal: {
      type: Boolean,
      default: false,
      // true  → platform-level metric, no clientId
      // false → client-scoped custom metric, clientId required
    },
    clientId: {
      type: String,
      default: null,
      // null for global metrics; set for client-scoped metrics.
    },

    // ── Measurement (§2.2) — minimal ──────────────────────────────────────────
    primaryUnit: {
      type: String,
      trim: true,
      default: null,
      // e.g. 'GJ', 'tCO2e', '%', 'kWh'
    },
    allowedUnits: {
      type: [String],
      default: [],
      // optional alternative units accepted for this metric
    },
    dataType: {
      type: String,
      enum: DATA_TYPE_ENUM,
      default: 'number',
    },

    // ── Formula reference (§2.5 — minimal, no variable mode mapping) ──────────
    formulaId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Formula',         // was: 'ReductionFormula' — updated to match common Formula model name
      default: null,
      // Required when metricType is 'derived' or 'intensity'.
      // Variable mode mapping (frozen / realtime / manual) is deferred to Step 3.
    },

    // ── Lifecycle / status ─────────────────────────────────────────────────────
    publishedStatus: {
      type: String,
      enum: PUBLISHED_STATUS_ENUM,
      default: 'draft',
      // Global metrics:         draft → published → retired
      // Client-scoped metrics:  immediately 'published' on creation
    },
    version: {
      type: Number,
      default: 1,
      // Increments when any definition-level field is updated (name, unit, formula,
      // type, category, subcategory, description). Status changes do NOT bump version.
    },
    publishedAt: {
      type: Date,
      default: null,
    },
    retiredAt: {
      type: Date,
      default: null,
    },

    // ── Measurement & Collection ──────────────────────────────────────────────
    frequency: {
      type: String,
      enum: ['daily', 'weekly', 'monthly', 'quarterly', 'semi_annual', 'annual', 'as_needed', null],
      default: null,
      // Applicable primarily to raw metrics.
    },
    boundaryScope: {
      type: String,
      enum: ['site', 'entity', 'organization', 'value_chain', 'product', null],
      default: null,
    },
    sourceType: {
      type: String,
      enum: ['manual_entry', 'iot_sensor', 'financial_system', 'survey', 'calculated', 'third_party', null],
      default: null,
    },
    rollUpBehaviour: {
      type: String,
      trim: true,
      default: null,
      // Code referencing an EsgRollUpBehavior document (e.g. 'sum', 'average', 'last').
    },

    // ── Reporting ─────────────────────────────────────────────────────────────
    reportingUnitNote: {
      type: String,
      trim: true,
      default: null,
    },
    reportingLevelNote: {
      type: String,
      trim: true,
      default: null,
    },

    // ── Data Collection / Integration ─────────────────────────────────────────
    zeroCarbonReference: {
      type: String,
      trim: true,
      default: null,
      // Reference field path in the zero_carbon module (e.g. 'scope1.fuelCombustion').
    },
    ingestionInstruction: {
      type: String,
      trim: true,
      default: null,
    },

    // ── Validation & Evidence ─────────────────────────────────────────────────
    validationRule: {
      type: String,
      trim: true,
      default: null,
      // Human-readable validation description (e.g. 'Must be > 0', 'Range: 0–100%').
    },
    evidenceRequirement: {
      type: String,
      enum: ['none', 'optional', 'required', 'mandatory', null],
      default: null,
    },

    // ── Admin / governance metadata (§2.10) ───────────────────────────────────
    isBrsrCore: {
      type: Boolean,
      default: false,
    },
    regulatorySourceRef: {
      type: String,
      trim: true,
      default: null,
    },
    notesForUi: {
      type: String,
      trim: true,
      default: null,
    },

    // ── Framework mapping cache (auto-maintained by metricFrameworkSyncService) ──
    // Source of truth is QuestionMetricMapping collection; this array is a
    // denormalised cache rebuilt after every mapping create/update/delete.
    // Do NOT write this field directly — call syncMetricFrameworkFlags(metricId).
    frameworkMappings: {
      type: [
        {
          frameworkCode:  { type: String },
          questionCode:   { type: String },
          sectionCode:    { type: String },
          principleCode:  { type: String },
          indicatorType:  { type: String },
          isCore:         { type: Boolean, default: false },
          mappingId:      { type: mongoose.Schema.Types.ObjectId },
          _id:            false,
        },
      ],
      default: [],
    },

    // ── Ownership ─────────────────────────────────────────────────────────────
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'createdBy is required'],
    },
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },

    // ── Soft delete ───────────────────────────────────────────────────────────
    isDeleted: {
      type: Boolean,
      default: false,
    },
    deletedAt: {
      type: Date,
      default: null,
    },
    deletedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
  },
  {
    timestamps: true,   // createdAt, updatedAt auto-managed
    versionKey: false,
    collection: 'esg_metrics',
  }
);

// ── Indexes ────────────────────────────────────────────────────────────────────

// Unique metric code within scope
// Global metrics: unique across all global metrics
// Client-scoped:  unique per client — partial unique index handled at app layer;
//                 sparse prevents null collision on metricCode
esgMetricSchema.index({ metricCode: 1 }, { unique: true, sparse: true });

// Fast lookup for list-global-metrics endpoint
esgMetricSchema.index({ isGlobal: 1, publishedStatus: 1, isDeleted: 1 });

// Fast lookup for list-client-metrics endpoint
esgMetricSchema.index({ clientId: 1, publishedStatus: 1, isDeleted: 1 });

// Domain filtering
esgMetricSchema.index({ esgCategory: 1, subcategoryCode: 1 });

// Code-generation counter queries
esgMetricSchema.index({ isGlobal: 1, esgCategory: 1, subcategoryCode: 1, isDeleted: 1 });
esgMetricSchema.index({ clientId: 1, esgCategory: 1, subcategoryCode: 1, isDeleted: 1 });

// Framework mapping cache queries
esgMetricSchema.index({ isBrsrCore: 1, 'frameworkMappings.frameworkCode': 1 });

// ── Exports ────────────────────────────────────────────────────────────────────

module.exports = mongoose.model('EsgMetric', esgMetricSchema);
module.exports.SUBCATEGORY_CODES      = SUBCATEGORY_CODES;
module.exports.METRIC_TYPE_ENUM       = METRIC_TYPE_ENUM;
module.exports.ESG_CATEGORY_ENUM      = ESG_CATEGORY_ENUM;
module.exports.DATA_TYPE_ENUM         = DATA_TYPE_ENUM;
module.exports.PUBLISHED_STATUS_ENUM  = PUBLISHED_STATUS_ENUM;
