'use strict';

/**
 * Normalize an allocation payload before persisting.
 *
 * Rules agreed with product:
 *   category_code  = categoryName.toUpperCase()
 *   facility_id    = nodeLabel  (human-readable location name)
 *   source_code    = supplied value (auto-generated by createAllocation before calling here)
 *   business_unit_id = null  (manual field, never overwritten here)
 *
 * On UPDATE the caller must strip keys it doesn't want to touch rather
 * than relying on this function to skip them.
 */
function normalizeAllocationPayload(data) {
  const scopeDetailAllocationPct =
    data.scopeDetailAllocationPct ?? data.allocated_pct ?? 100;

  return {
    ...data,

    // Numeric allocation percentages
    allocated_pct:            Number(data.allocated_pct ?? scopeDetailAllocationPct),
    scopeAllocationPct:       Number(data.scopeAllocationPct ?? 100),
    categoryAllocationPct:    Number(data.categoryAllocationPct ?? 100),
    nodeAllocationPct:        Number(data.nodeAllocationPct ?? 100),
    scopeDetailAllocationPct: Number(scopeDetailAllocationPct),
    absoluteAllocatedValue:   Number(data.absoluteAllocatedValue ?? 0),

    // Derived identity fields
    category_code: (data.category_code || data.categoryName || 'UNCATEGORIZED').toUpperCase(),
    facility_id:   data.facility_id || data.nodeLabel || data.nodeId || '',

    // source_code must be explicitly set by the caller — never fallback to undefined
    ...(data.source_code ? { source_code: data.source_code } : {}),
  };
}

module.exports = { normalizeAllocationPayload };
