'use strict';

// ============================================================================
// markdownExporter.js — Converts a report data model into a markdown string
//
// Uses normalizeTable() so all four column/row shapes are handled correctly:
//   A: columns=[{key,label}], rows=[{key:val}]   ← query response
//   B: columns=['string'],    rows=[{key:val}]
//   C: columns=['string'],    rows=[['v1','v2']]  ← legacy report service
//   D: columns=[{key,label}], rows=[['v1','v2']]
// ============================================================================

const { normalizeTable } = require('./tableNormalizer');

/**
 * @param {object} reportData  — from reportService.assembleReportData() or
 *                               exportService._toReportDataShape()
 * @returns {string}  markdown string
 */
function toMarkdown(reportData) {
  const lines = [];
  const { meta, sections } = reportData;

  lines.push(`# ${meta.title || 'GreOn IQ Report'}`);
  lines.push('');
  if (meta.clientName) lines.push(`**Client:** ${meta.clientName}`);
  if (meta.period)     lines.push(`**Period:** ${meta.period}`);
  lines.push(`**Generated:** ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const section of (sections || [])) {
    lines.push(`## ${section.heading}`);
    lines.push('');

    if (section.narrative) {
      lines.push(section.narrative);
      lines.push('');
    }

    for (const table of (section.tables || [])) {
      const norm = normalizeTable(table);

      lines.push(`### ${norm.title}`);
      lines.push('');

      if (norm.columns.length === 0) {
        lines.push('*No columns available.*');
        lines.push('');
        continue;
      }

      // Header row
      lines.push('| ' + norm.columns.map((c) => _mdEsc(c.label)).join(' | ') + ' |');
      // Separator
      lines.push('| ' + norm.columns.map(() => '---').join(' | ') + ' |');
      // Data rows
      for (const row of norm.rows) {
        lines.push('| ' + norm.columns.map((col) => _mdEsc(String(row[col.key] ?? '—'))).join(' | ') + ' |');
      }

      if (norm.totalRows > norm.rows.length) {
        lines.push(`*Showing ${norm.rows.length} of ${norm.totalRows} records.*`);
      }
      lines.push('');
    }
  }

  if (reportData.exclusions?.length) {
    lines.push('---');
    lines.push('');
    lines.push('## Data Exclusions');
    lines.push('');
    for (const excl of reportData.exclusions) {
      lines.push(`- ${excl}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Report generated by GreOn IQ. Data sourced from internal systems only.*');

  return lines.join('\n');
}

// Escape pipe characters and newlines so they don't break markdown tables
function _mdEsc(str) {
  return String(str).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

module.exports = { toMarkdown };
